#!/bin/bash
cd $(dirname "$(readlink -f "$0")")
list=$(find `ls | sed -e 's/^init$//'` -type f)
dir="$(pwd)"
cd
for i in $list; do
    if [[ -f ".$i" ]]; then
        mv ".$i" ".$i.OLD"
    fi
    if [[ $i =~ / ]]; then
        mkdir -p ".${i%/*}"
    fi
    ln "$dir/$i" ".$i"
done
#git clone git@github.com:xayon40-12/.vim && ~/.vim/init
git clone git@github.com:xayon40-12/.doom.d && ~/.doom.d/install
