#!/usr/bin/env zsh
cd "${0:a:h}" || (echo "cd into dotfile directory failed"; exit)
git pull

update() {
  if [[ -f "$1" ]]; then
    echo update: $1
    if [[ -f "$HOME/.$1.OLD" ]]; then
        rm "$HOME/.$1.OLD"
    fi
    if [[ -f "$HOME/.$1" ]]; then
        cp -L "$HOME/.$1" "$HOME/.$1.OLD"
        rm "$HOME/.$1"
    fi
    if [[ $1 =~ / ]]; then
        mkdir -p "$HOME/.${1%/*}"
    fi
    ln -s $(pwd)/"$1" "$HOME/.$1"
  fi
}

pushd all
  for i in **/*; do
    update $i
  done
popd

if [[ $1 == "arch" ]]; then
  pushd arch
    for i in **/*; do
      update $i
    done
  popd
fi

if [[ $1 == "macos" ]]; then
  pushd macos
    for i in **/*; do
      update $i
    done
  popd
fi
