theme = "monokai_pro"

[editor]
soft-wrap.enable = true
auto-pairs = false
cursorline = true
cursorcolumn = true
auto-save = true
idle-timeout = 100
bufferline = "multiple"

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "┊" # "▏", "┊", "⸽"
skip-levels = 0