# theme = "monokai_pro"
theme = "catppuccin_mocha"

[editor]
soft-wrap.enable = true
auto-pairs = false
cursorline = true
cursorcolumn = true
auto-save = true
idle-timeout = 100
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "error"

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.normal.space]
t = ["yank_to_clipboard", ":sh pbpaste | xargs sdcv -u org.edrdg.jmdict-jpn-eng -n"]

[keys.select.space]
t = ["yank_to_clipboard", ":sh pbpaste | xargs sdcv -u org.edrdg.jmdict-jpn-eng -n"]

[keys.normal.space.l]
l = [":pipe-to add_to_ltex_dict", ":config-reload", ":lsp-restart"]
w = ":lsp-workspace-command"
p = ":lsp-workspace-command tinymist.startDefaultPreview"
