[language-server.nu]
command = "nu"
args = ["--lsp"]

[[language]]
name = "nu"
language-servers = [ "nu" ]

[language-server.mdpls]
command = "mdpls" 
config = { markdown.preview.auto = true, markdown.preview.serveStatic	= true}

[[language]]
name = "markdown"
language-servers = [ "mdpls", "marksman" ]

[language-server.uiua]
command = "uiua"
args = ["lsp"]

[[language]]
name = "uiua"
scope = "source.ua"
roots = ["main.ua"]
file-types = ["ua"]
language-servers = ["uiua"]
auto-format = true
