[[language]]
name = "markdown"
language-server = { command = "mdpls" }
# config = { markdown.preview.auto = true, markdown.preview.browser = "firefox"}
config = { markdown.preview.auto = true, markdown.preview.serveStatic	= true}