#!/bin/zsh

if [[ "$(tty)" =~ "^/dev/tty(1|2)$" ]]; then
    exec startx
    exit 0
fi

# ************************ ZSH CONFIG ************************

# history
setopt PROMPT_SUBST
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt histignorealldups sharehistory

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
#eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# vim key binding
bindkey -v

# key bindings
export KEYTIMEOUT=1
#bindkey -M vicmd '?' history-incremental-pattern-search-backward
bindkey -M viins '^R' history-incremental-pattern-search-backward
#bindkey -M vicmd '/' history-incremental-pattern-search-forward
bindkey -M viins '^F' history-incremental-pattern-search-forward

# prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
function zle-keymap-select() {
  zle reset-prompt
  zle -R
}
zle -N zle-keymap-select
function vi_mode_prompt_info() {
  echo "${${KEYMAP/vicmd/[NORMAL]}/(main|viins)/[INSERT]}"
}
export PS1=$'%F{cyan}%n%f@%F{green}%M%f:%F{yellow}%~%F{blue}$(parse_git_branch)%f\n %(?..%F{red}\a)%#%f '
export RPS1='%F{magenta}$(vi_mode_prompt_info)%f'

# ************************ USR CONFIG ************************


# poweroff
alias pf="sudo poweroff"

# editors
alias se='sudoedit'
alias nv='nvim'
export EDITOR=hx #$(if command -v nvim &> /dev/null; then echo nvim; else echo vim; fi) #'emacsclient -t -a ""'
alias e=$EDITOR
ew() {emacsclient -c -a "" $* & disown}

# config files
alias vimrc="$EDITOR ~/.vim/vimrc"
alias nvimrc="$EDITOR ~/.config/nvim/init.vim"
alias zshrc="$EDITOR ~/.zshrc"
alias kakrc="$EDITOR ~/.config/kak/kakrc"
alias zshlocal="$EDITOR ~/.zsh_local"

# color alias
alias ls="ls --color=auto"
alias grep='grep --color=auto'


if [[ `uname` == "Darwin" ]]; then
  alias o='open >/dev/null 2>&1'
else
  #terminal clipboard (need to install xclip)
  alias pbcopy="xclip -selection c"
  alias pbpaste="xclip -selection clipboard -o"
fi

#open files with type detection

if command -v handlr &> /dev/null; then
  alias open="handlr open" #"xdg-open"
fi
alias o='open >/dev/null 2>&1'

# rust
docrs() { firefox "https://docs.rs/$1" }
alias cb="cargo build"
alias cr="cargo run"
alias cbr="cargo build --release"
alias ct="RUSTFLAGS=\"$RUSTFLAGS -A dead_code\" cargo test -- --nocapture"
alias cs="cargo script"

# utilities
export PATH=~/u:$PATH
export PATH="$HOME/.local/bin:$PATH"
alias dev='cd $(cat ~/.current_dev)'
alias sdev='pwd > ~/.current_dev'

#disable legacy terminal xon (ctrl-s and ctrl-q)
stty -ixon

# rust cargo
export PATH="$HOME/.cargo/bin:$PATH"
alias cargogitinstall='cargo install --path $(git rev-parse --show-toplevel)'

# mount
alias smount='sudo mount -o gid=users,fmask=113,dmask=002'
alias sumount='sudo umount'

# ssh
alias ssht='TERM=xterm-256color ssh'

#sympy
alias sym='ipython -i ~/.sympy_setup_mat.py'
alias symphy='ipython -i ~/.sympy_setup_phy.py'

# launch neofetch when terminal start
#neofetch

#start terminal in preceding directory
alias bcd='builtin cd'
function cd() {
    builtin cd $1
    pwd > ~/.current_term_dir
}
eval "$(zoxide init bash)"
function z() {
  __zoxide_z $@
  pwd > ~/.current_term_dir
}
function zi() {
  __zoxide_zi $@
  pwd > ~/.current_term_dir
}
cd "$(cat ~/.current_term_dir)"

# for d in d p x y z w dl; do
#     alias $d="cd ~/$d"
# done

#ranger
export RANGER_LOAD_DEFAULT_RC=FALSE

#bashtop
alias top='$(command -v bashtop || command -v htop || command -v top)'

#notes
alias n='e $HOME/notes/notes.md'
alias td='e $HOME/notes/todo.md'

#regex search
regex () {
	awk 'match($0,/'$1'/, ary) {print ary['${2:-'0'}']}'
}

#haskell
export PATH=$HOME/.ghcup/bin:$PATH
alias ghciconf="$EDITOR ~/.ghc/ghci.conf"
#alias ghci='stack ghci +RTS -M8192M -c30 -RTS'
alias hswatch="echo **/*.{hs,cabal,yaml} | sed 's/ /\n/g' | entr -rc stack run"
alias hswatchtest="find . -name '*.hs' | entr -rc stack test"
alias hs="ptghci"
#idris2
alias idrisi="rlwrap idris2"

#update pacman mirror list
export country=japan
alias pacmirror='sudo reflector --verbose --country '$country' -l 15 -p http --sort rate --save /etc/pacman.d/mirrorlist'

#terminal program alias
alias ls='$(if command -v exa &> /dev/null; then echo "exa -lga"; else echo "ls"; fi)'

#set numeric to english
export LC_NUMERIC=en_US.UTF-8

alias size='du -h --max-depth 1 | sort -h'
alias icat="kitty +kitten icat"








if [[ -f ~/.zsh_local ]] ; then
    . ~/.zsh_local
fi

#WARING must stay at the end
#starship prompt
eval "$(starship init zsh)"
